env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=jensens/bandersnatch-docker
  - secure: RlptBYC+RVbPhXqMC3yDObiWUmQNHR7EHfSIxJkzSz1/ASuoQ9VeJ5OCzX1wHulw6dLgKH6+6Jnu2LO5wkFArVZ7wm4U1cNgnakEZ6BxjFLk3qblsYhXYPX0w59/MDffijLVHPLoCZEEm47IPJftL8w2OLuekVJZFNyALOLHqmqCAnH1wvFwyWrrR4Z2beuBgMcPjEMaIbKOy/+eFmfEX3WAT715MuajkRbO6QpEygMWCUbIc/HzruH/7ELElHdvZNASVz2VuxTFa2ZyOHrypoCNRmv7XphCbtTFsvI4jDDaVKZq3oRraadv+7OBnfg/1iLse1Y0/H5fa1a9ukYv+2nHMpvvzkNh+ShZtBX8vryheQgL9wK0gPWC96/e8lYKakw9djciPKOLm40lAjTOWNygPpxfeJOy1i8zoITDDS8f7u5aNyuFO5QOCjyw5Cz5yNOMfxEZLYb9tuMirl95YE4EosK0Xzmetj30wJ8W7oa4GOwu6DcJuXct4DbIbi/FEiSOrA2MrfD2afcBL5SvVn6RI6gGqI7kyTUR3IAFMmeQ5hffBB45IK3q0PuDS1//ImQzlvPKmFvqxPX7YChG5vRpnoTi8pziOltvwWwolms4Nqo/k1IN+gwp1k0fzq/ui1l6tJkPc26AY9DtMPmYgFrEvWMervUhCL+4pMIgLcE=
  - secure: UeGjM3Ht8pjF9Wwo/oSTZvUp7AKsgV5xDEe95hum79rsQYC30S9O2XqDYsa55MujBDo88vqWKw3OKP91lrgVEAo5GHb9QUf5ySmwod2mP55sAwLdH4lBcMjojR30W+MGxaAfAVhrUNE6rID6o07Tf2hKpS/sCVa4CgFnGx5pfKJIujtnWSeRwBJgNVYTSAKNG/s2177rlXD/n/xznauwVv0gL2A8MRpez5Kwblo2JkN0ylqVYynENE6FxwALp6m25r/XQ47UohGqLK20S4FtLrajF+ixDM6cELj7cXJT+W5YYN+/KobEm9Il2B48FJwlea5Zyfl68xoGeMti3xQDeXm2DJuQaFOM6mMlau2sSUNZ4YvyxMYh5BWH+IsLm6bEhi8jNtwpKoJ5/kFcQswtsTG3ZSw18npxRzV4wzW5JZ5lY+tni6bcEKA6a2af5fY8Sm2JM0fZKGu9i3akKihLy+HR4WpYTIQIxge4nlrJ9y0qCDVz6PlSgie0RIrEvvRKVvsvImcaEBMDOftSKPCOsV/Opc0lu425Go07DnCVdagifI/kV40WOYiiUH6h0chSF12qEJ2/s2QKOpNr6cgUwstQ2hC2ztfxBbsQZSVMd6MDsOgkuCqVRpdwfal0fkcTezIWYMYVOEyHTkMScUrBjxNV8FzsDfMcBGzxvPWzIrs=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=jensens/bandersnatch
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
 - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
   docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
   docker push $REPO:$TRAVIS_BUILD_NUMBER;
   fi
 - docker push $REPO:$TAG
