env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=jensens/bandersnatch-docker
  - secure: e+pw0UhApUb5QfFdFAPdQx1Ky7mUj+wO/FuE4yJajUsLBw7P+6nN5UHj8/eW4DLoXZH8cH+yPOAs76upR/uYCyegDZ4bD09CKx6cizhBUWUwvW2JHwB3dwaysJpT9zbgA46M80AUM37IlvXtKzPgY3L/9UMQ8Hi7ZoKCqvSKh3Q1pTROYUAPTKcyU0OrmpKFFw0a3336wM8N/H3QBAHcmIy6hxCziuHhQ/TpeHmXQNv3H7+xE5K4f51iSWqRUkFjAKG+WaGOh7g2NA8QM1VcSj+u3pQRIXd1KUZq+xe0LI4TBVjeNAIHJlHep1kP921Sr4CBb8adELd+C7RBnAOP/IU2kdecpiI3y4ff5y4ZBndv/FSNUsEAk7rhZPaG5NWLqsgW1qWP3BtzPrNQovNHybw4F0bPqivkhDtZ3KjI4bVfXdG8N1PScPd2uC1/g8IsfM/9mi+jwfea9tgK549x5Vj7MzT+Npl6kwW/VBa+II+dLsSisWF8a5TJJU9crQ/a6V4xzt6Ow9dS/cdr+LRzKzJPZJropZF/KvBsKoYg8QoM2gbs0ivr0lQuIuFtECHKKfYdDTbDaWeHGLgYmHp0/vlKpqmbmz2oAEnV/mLigOfCy/P6MUynXbUyOngCJHVh5PYgWPY3f03qQGQkyG34hT0WAwp3CW5RTD/AJgEcSBc=
  - secure: pHlJv24QUfJ1rHtdXd7KnpVgMgAIK1xWWKts0LnovQeFh5yFSQMnINzWbyT8wi5vp6Ra1NWXTloqKLS52dXAlJ2JLQOQd4K1IyoaqAKOrGSMjCBBmCR+0QfbUeCdAnR3fcKE53Ola/0C4Gk2+/Ux1HV6J64qf1Hf38w89Tt09EaoofQy500YOVP4Bp4xUyFjUf+JdqHeacfpng/MEUAicZ90+lZaSEQV9H7TP7i5kat46DxODk0WwAUgAupbRifKmsjdnfqXeL5VxLt8HBx8eIKA7Toeyb/f2FpoKN3Ens25dICzGwLrZa0VhWAF0V4YJEzLyfC7Q1tSWA9yVQ6XcpwefZrStYjo7uDg4ZXv0xd38sY+ZYfKIPPIU8WfOwOkLSjAKQ4RY7TXadXJLQQzsmPijWLo9j+vgzSaJ649j6/l2BIOZWQQ3TCrVIEIvqladV9Ao+/vw+UOhHJB//FvqjI0WeNkOj3I2WNuwbJiehEJZJ2NvHZlp2rN0m7qdqRQSO4wb46Mch9PVRzl9Qac4TwrWf8hrykaAxumlqIPdnJSD2UybdJEZytQNusN3Sx7vkQdOj2ZEhGP9q2qqyBRalZ8rohcx+wqt084Qq2bvLBh0gTLY8F4e0SnNvv+vynDmyejtqSx2H9J26szo2p8BfzV/kcbN5EI1RobAhmXb/4=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=jensens/bandersnatch
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
